Add promoting script

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -151,8 +151,8 @@ jobs:
       - name: CodeCov
         uses: codecov/codecov-action@v4
 
-  build-gradle-project:
-    when:
+  Publish-Artifacts:
+    needs:
       - API-Tests
       - Component-Tests
       - End-To-End-Tests
@@ -185,3 +185,49 @@ jobs:
         env:
           # AZURE_TOKEN with Packaging (Read, write, & manage); Release (Read, write, execute, & manage)
           AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
+
+  Promote-Artifacts:
+    needs:
+      - Publish-Artifacts
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Promote artifacts"
+        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+        env:
+          # AZURE_TOKEN with Packaging (Read, write, & manage); Release (Read, write, execute, & manage)
+          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
+        run: |
+          # Core EDC https://dev.azure.com/sovity/Core%20EDC
+          PROJECT="41799556-91c8-4df6-8ddb-4471d6f15953"
+          #core-edc feed https://dev.azure.com/sovity/Core%20EDC/_artifacts/feed/core-edc
+          FEED="core-edc"
+          
+          curl -u ":$AZURE_TOKEN" \
+          "https://feeds.dev.azure.com/sovity/$PROJECT/_apis/packaging/Feeds/$FEED/packages?protocolType=maven&includeUrls=false&includeAllVersions=true&includeDeleted=false&api-version=7.0" \
+          | jq --raw-output '.value[].name' | cut -d ':' -f 2 | while read -r arti
+          do
+            echo "Promoting $arti ..."
+            curl \
+              -X PATCH \
+              -u ":$AZURE_TOKEN" \
+              "https://pkgs.dev.azure.com/sovity/$PROJECT/_apis/packaging/feeds/core-edc/maven/groups/org.eclipse.edc/artifacts/${arti}/versions/${VERSION}?api-version=7.1-preview.1" \
+              --json @- <<"EOF"
+          {
+            "views": {
+              "op": "add",
+              "path": "/views/-",
+              "value": "Release"
+            }
+          }
+          
+          EOF
+          
+          if [[ $? -ne 0 ]]
+          then
+            echo "Failed to promote $arti"
+            exit 1
+          else
+            echo "Promoted $arti"
+          fi
+          
+          done
