0.11.1 fork setup (#39)

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -3,9 +3,9 @@ name: Run Tests
 on:
   workflow_dispatch:
   push:
-    branches: [ main, release/*, bugfix/* ]
+    branches: [ main, release/*, bugfix/*, sovity/* ]
   pull_request:
-    branches: [ main, release/*, bugfix/* ]
+    branches: [ main, release/*, bugfix/*, sovity/* ]
     paths-ignore:
       - "**.md"
       - "docs/**"
@@ -16,16 +16,20 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+env:
+  # AZURE_TOKEN with Packaging (Read, write, & manage); Release (Read, write, execute, & manage)
+  AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
+
 jobs:
-  CodeQL:
-    uses: eclipse-edc/.github/.github/workflows/codeql-analysis.yml@main
-    secrets: inherit
+#  CodeQL:
+#    uses: sovity/core-edc-github/.github/workflows/codeql-analysis.yml@0.11.1_2025-03-10_1
+#    secrets: inherit
 
   Checkstyle:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: eclipse-edc/.github/.github/actions/setup-build@main
+      - uses: sovity/core-edc-github/.github/actions/setup-build@0.11.1_2025-03-10_1
       - name: Run Checkstyle
         run: ./gradlew checkstyleMain checkstyleTest checkstyleTestFixtures
 
@@ -33,7 +37,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: eclipse-edc/.github/.github/actions/setup-build@main
+      - uses: sovity/core-edc-github/.github/actions/setup-build@0.11.1_2025-03-10_1
       - name: Run Javadoc
         run: ./gradlew javadoc
 
@@ -41,7 +45,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: eclipse-edc/.github/.github/actions/setup-build@main
+      - uses: sovity/core-edc-github/.github/actions/setup-build@0.11.1_2025-03-10_1
       - name: Run unit tests
         run: ./gradlew test
 
@@ -58,7 +62,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-      - uses: eclipse-edc/.github/.github/actions/setup-build@main
+      - uses: sovity/core-edc-github/.github/actions/setup-build@0.11.1_2025-03-10_1
       - name: Postgresql Tests
         run: ./gradlew test -DincludeTags="PostgresqlIntegrationTest"
 
@@ -66,7 +70,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: eclipse-edc/.github/.github/actions/setup-build@main
+      - uses: sovity/core-edc-github/.github/actions/setup-build@0.11.1_2025-03-10_1
       - name: End to End Integration Tests
         run: ./gradlew test -DincludeTags="EndToEndTest"
 
@@ -74,7 +78,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: eclipse-edc/.github/.github/actions/setup-build@main
+      - uses: sovity/core-edc-github/.github/actions/setup-build@0.11.1_2025-03-10_1
       - name: Component Tests
         run: ./gradlew test -DincludeTags="ComponentTest"
 
@@ -82,12 +86,97 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: eclipse-edc/.github/.github/actions/setup-build@main
+      - uses: sovity/core-edc-github/.github/actions/setup-build@0.11.1_2025-03-10_1
       - name: Component Tests
         run: ./gradlew test -DincludeTags="ApiTest"
 
-  Verify-OpenApi:
-    if: github.event_name == 'pull_request'
-    uses: eclipse-edc/.github/.github/workflows/verify-openapi.yml@main
-    secrets: inherit
+# This refuses to work, because it uses a task that would now depend on our Azure repo, for which I didn't find how to
+# pass the credentials and it's not a critical task, we only fork for a single version and on the next version we can
+# forget about this, either because the root cause vanished, the task went somewhere else, or whatever may happen,
+# noone knows...
 
+#  Verify-OpenApi:
+#    if: github.event_name == 'pull_request'
+#    uses: sovity/core-edc-github/.github/workflows/verify-openapi.yml@0.11.1_2025-03-10_1
+#    secrets: inherit
+
+  Publish-Artifacts:
+    needs:
+      - API-Tests
+      - Component-Tests
+      - End-To-End-Tests
+      - Postgresql-Integration-Tests
+      - Unit-Tests
+
+    name: Publish artefacts
+    runs-on: ubuntu-latest
+    timeout-minutes: 360
+    permissions:
+      contents: read
+      packages: write
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: "Gradle: Publish to Production"
+        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+        run: |
+          GRADLE_ARGS="-Pversion=${GITHUB_REF#refs/tags/v}"
+          ./gradlew --parallel "$GRADLE_ARGS" publishAllPublicationsToAzureRepository
+        env:
+          # AZURE_TOKEN with Packaging (Read, write, & manage); Release (Read, write, execute, & manage)
+          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
+
+      - name: "Gradle: Publish to Test"
+        if: ${{ startsWith(github.ref, 'refs/heads/sovity/') }}
+        run: |
+          GRADLE_ARGS="-Pversion=${GITHUB_REF#refs/heads/sovity/}.0.$(date '+%Y%m%d.%H%M%S')"
+          ./gradlew --parallel "$GRADLE_ARGS" publishAllPublicationsToAzureTestRepository
+        env:
+          # AZURE_TOKEN with Packaging (Read, write, & manage); Release (Read, write, execute, & manage)
+          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
+
+  Promote-Artifacts:
+    needs:
+      - Publish-Artifacts
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Promote artifacts"
+        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+        env:
+          # AZURE_TOKEN with Packaging (Read, write, & manage); Release (Read, write, execute, & manage)
+          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
+        run: |
+          # Core EDC https://dev.azure.com/sovity/Core%20EDC
+          PROJECT="41799556-91c8-4df6-8ddb-4471d6f15953"
+          #core-edc feed https://dev.azure.com/sovity/Core%20EDC/_artifacts/feed/core-edc
+          FEED="core-edc"
+          
+          curl -u ":$AZURE_TOKEN" \
+          "https://feeds.dev.azure.com/sovity/$PROJECT/_apis/packaging/Feeds/$FEED/packages?protocolType=maven&includeUrls=false&includeAllVersions=true&includeDeleted=false&api-version=7.0" \
+          | jq --raw-output '.value[].name' | cut -d ':' -f 2 | while read -r arti
+          do
+            echo "Promoting $arti ..."
+            curl \
+              -X PATCH \
+              -u ":$AZURE_TOKEN" \
+              "https://pkgs.dev.azure.com/sovity/$PROJECT/_apis/packaging/feeds/core-edc/maven/groups/org.eclipse.edc/artifacts/${arti}/versions/${VERSION}?api-version=7.1-preview.1" \
+              --json @- <<"EOF"
+          {
+            "views": {
+              "op": "add",
+              "path": "/views/-",
+              "value": "Release"
+            }
+          }
+          
+          EOF
+          
+          if [[ $? -ne 0 ]]
+          then
+            echo "Failed to promote $arti"
+            exit 1
+          else
+            echo "Promoted $arti"
+          fi
+          
+          done
